//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblActor
    {
        public int ActorId { get; set; }
        public string ActorName { get; set; }
        public string ActorSurname { get; set; }
        public Nullable<System.DateTime> ActorDt { get; set; }
        public string ActorDetails { get; set; }
        public Nullable<int> MovieId { get; set; }
        public Nullable<int> TvSeriesId { get; set; }
        public Nullable<int> ActorPhotoId { get; set; }
        public string ActorPhotoUrl { get; set; }
    
        public virtual TblMovie TblMovie { get; set; }
        public virtual TblTvSeries TblTvSeries { get; set; }
    }
}
