//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblKisiGezinti
    {
        public int Id { get; set; }
        public Nullable<int> KisiId { get; set; }
        public Nullable<int> KullaniciId { get; set; }
        public Nullable<int> MovieId { get; set; }
        public Nullable<int> TvSeriesId { get; set; }
    
        public virtual TblKisi TblKisi { get; set; }
        public virtual TblKullanici TblKullanici { get; set; }
        public virtual TblMovie TblMovie { get; set; }
        public virtual TblTvSeries TblTvSeries { get; set; }
    }
}
