//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMoviePhoto
    {
        public int MoviePhotoId { get; set; }
        public int MovieId { get; set; }
        public string MoviePhotoUrl { get; set; }

        public string MovieName { get; set; }
        public Nullable<bool> MovieAcilis { get; set; }
    
        public virtual TblMovie TblMovie { get; set; }
    }
}
