//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMovieComment
    {
        public int MovieCommentId { get; set; }
        public int MovieId { get; set; }
        public string MovieComment { get; set; }
        public Nullable<System.DateTime> MovieCommentDt { get; set; }
        public Nullable<int> KisiId { get; set; }
        public Nullable<int> KullaniciId { get; set; }
    
        public virtual TblMovie TblMovie { get; set; }
    }
}
