//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMovie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblMovie()
        {
            this.TblActor = new HashSet<TblActor>();
            this.TblDirector = new HashSet<TblDirector>();
            this.TblKisiGezinti = new HashSet<TblKisiGezinti>();
            this.TblMovieComment = new HashSet<TblMovieComment>();
            this.TblMoviePhoto = new HashSet<TblMoviePhoto>();
            this.TblMovieVideo = new HashSet<TblMovieVideo>();
        }
    
        public int MovieId { get; set; }
        public string MovieName { get; set; }
        public string MovieDetails { get; set; }
        public int CategoryId { get; set; }
        public Nullable<int> ReleaseDate { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<int> Goruntulenme { get; set; }
        public string MovieSeo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblActor> TblActor { get; set; }
        public virtual TblCategory TblCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDirector> TblDirector { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblKisiGezinti> TblKisiGezinti { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMovieComment> TblMovieComment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMoviePhoto> TblMoviePhoto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMovieVideo> TblMovieVideo { get; set; }
    }
}
