//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMovieVideo
    {
        public int MovieVideoId { get; set; }
        public string MovieVideoUrl { get; set; }
        public int MovieId { get; set; }
    
        public virtual TblMovie TblMovie { get; set; }
    }
}
