//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblTvSeries
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblTvSeries()
        {
            this.TblActor = new HashSet<TblActor>();
            this.TblDirector = new HashSet<TblDirector>();
            this.TblKisiGezinti = new HashSet<TblKisiGezinti>();
            this.TblTvSeriesComment = new HashSet<TblTvSeriesComment>();
            this.TblTvSeriesPhoto = new HashSet<TblTvSeriesPhoto>();
            this.TblTvSeriesVideo = new HashSet<TblTvSeriesVideo>();
        }
    
        public int TvSeriesId { get; set; }
        public string TvSeriesName { get; set; }
        public string TvSeriesDetails { get; set; }
        public int CategoryId { get; set; }
        public Nullable<int> ReleaseDate { get; set; }
        public Nullable<int> Season { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<int> Goruntulenme { get; set; }
        public string TvSeriesSeo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblActor> TblActor { get; set; }
        public virtual TblCategory TblCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDirector> TblDirector { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblKisiGezinti> TblKisiGezinti { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblTvSeriesComment> TblTvSeriesComment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblTvSeriesPhoto> TblTvSeriesPhoto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblTvSeriesVideo> TblTvSeriesVideo { get; set; }
    }
}
